services:
  app:
    build: .
    container_name: fitness-app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      CLOUDINARY_CLOUD_NAME: dvvrff2pf
      CLOUDINARY_API_KEY: 814276854344398
      CLOUDINARY_API_SECRET: Gyi-o_es6an1-mpkVfWjXj6QTKc
      CLOUDINARY_URL: cloudinary://814276854344398:Gyi-o_es6an1-mpkVfWjXj6QTKc@dvvrff2pf

      SECRET_KEY: 2af97720e443f9db3b3b9b05633fb737f9441b560fe052f16dab513fb76327c4
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

      BCRYPT_ROUNDS: 12
      PEPPER_KEY: s0m3-r@nd0m-pepp3r-v@lu3

      DB_USER: root
      DB_PASSWORD: Sharma12345
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: helthTrackerApp

      REDIS_URL: redis://redis:6379/1

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sharma12345
      MYSQL_DATABASE: helthTrackerApp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
