"""Add membership_type to memberships

Revision ID: dad7556c629a
Revises: 396deb5904a3
Create Date: 2025-04-08 07:17:45.514297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dad7556c629a'
down_revision: Union[str, None] = '396deb5904a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
    op.add_column('memberships', sa.Column('membership_type', sa.String(length=50), nullable=False))
    op.drop_column('memberships', 'type')
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=False)
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_index(op.f('ix_trainers_name'), 'trainers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainers_name'), table_name='trainers')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.add_column('memberships', sa.Column('type', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('memberships', 'membership_type')
    op.alter_column('clients', 'email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
